"""
CPCB National AQI category breakpoints (0-500 scale). This is the grounding
table referenced in your plan doc Section 6 ("CPCB National Air Quality Index
— methodology document"). Source to cite in the paper:
https://cpcb.nic.in/National-Air-Quality-Index/

Every advisory generated by this system MUST trace back to one of these
categories — the LLM (if used at all) is only allowed to phrase/localize the
selected template, never invent a category or a numeric claim.
"""

AQI_CATEGORIES = [
    {"name": "Good", "range": (0, 50),
     "general": "Air quality is satisfactory. Enjoy outdoor activities as usual.",
     "sensitive": "No precautions needed."},
    {"name": "Satisfactory", "range": (51, 100),
     "general": "Air quality is acceptable. Minor breathing discomfort possible for unusually sensitive people.",
     "sensitive": "Consider reducing prolonged outdoor exertion if you notice symptoms."},
    {"name": "Moderate", "range": (101, 200),
     "general": "Breathing discomfort possible for people with lung disease, asthma, children, and older adults.",
     "sensitive": "Limit prolonged outdoor exertion. Keep rescue medication accessible."},
    {"name": "Poor", "range": (201, 300),
     "general": "Breathing discomfort likely on prolonged exposure for most people.",
     "sensitive": "Avoid prolonged or heavy outdoor exertion. Stay indoors with windows closed where possible."},
    {"name": "Very Poor", "range": (301, 400),
     "general": "Respiratory illness on prolonged exposure. Discomfort even on short exposure.",
     "sensitive": "Avoid all outdoor physical activity. Use an N95 mask if you must go out."},
    {"name": "Severe", "range": (401, 500),
     "general": "Affects healthy people and seriously impacts those with existing conditions.",
     "sensitive": "Stay indoors. Avoid all outdoor exertion. Seek medical attention if experiencing breathlessness, chest pain, or dizziness."},
]


def categorize(aqi_value: float) -> dict:
    aqi_value = max(0, min(500, aqi_value))
    for cat in AQI_CATEGORIES:
        lo, hi = cat["range"]
        if lo <= aqi_value <= hi:
            return cat
    return AQI_CATEGORIES[-1]
